INCEPTION_USERNAME = 'root'
INCEPTION_PASSWORD = ''
INCEPTION_HOST = '127.0.0.1'
INCEPTION_PORT = 6669

# MYSQL_USER = 'abel'
MYSQL_USER = 'abel_inception'
MYSQL_PASSWORD = 'asdfg'
MYSQL_HOST = '127.0.0.0'
MYSQL_PORT = 3306
